server:
  servlet:
    context-path: /forum
    session:
      cookie:
        path: /
  port: 8000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://35.244.106.99:3306/forum?characterEncoding=utf-8&useSSL=false&serverTimezone=Australia/Sydney
    username: root
    password: spm2020
  redis:
    host: localhost
    port: 6379
    database: 0
  mail:
    default-encoding: utf-8
    host: smtp.qq.com
    username: 1197150065@qq.com
    password: surlashrixtvhjca
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

mybatis:
  mapper-locations: classpath:touch/forum/mapper/*.xml
  type-aliases-package: touch.forum.entity

logging:
  config: classpath:logback-boot.xml
